# Generated by Django 5.1.4 on 2026-09-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_client_project_primary_team_projectteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budgeted_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='job_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='job_value_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
