# Generated by Django 5.1.4 on 2026-09-22 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_budgeted_hours_project_job_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Project key must be 2-100 uppercase letters/digits, starting with a letter.', regex='^[A-Z][A-Z0-9]{1,99}$')]),
        ),
    ]
