# Generated by Django 5.1.4 on 2026-09-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='task_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
