# Generated by Django 5.1.4 on 2026-09-25 12:42

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_requires_projects'),
        ('orgs', '0001_initial'),
        ('projects', '0005_project_task_names'),
        ('teams', '0002_team_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectKeyAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='is_client_workspace',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Project key must be 2-100 letters/digits, starting with a letter.', regex='^[A-Za-z][A-Za-z0-9]{1,99}$')]),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('key'), name='project_key_unique_ignoring_case'),
        ),
        migrations.AddField(
            model_name='projectkeyalias',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_aliases', to='projects.project'),
        ),
        migrations.AddConstraint(
            model_name='projectkeyalias',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('key'), name='project_key_alias_unique_ignoring_case'),
        ),
    ]
