# Generated by Django 5.1.4 on 2026-10-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_workspace_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='special_notes',
            field=models.TextField(blank=True),
        ),
    ]
