# Generated by Django 5.1.4 on 2026-10-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_workspace_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='avatar_color',
            field=models.CharField(default='#6A3DF0', max_length=7),
        ),
    ]
