# Generated by Django 5.1.4 on 2026-10-04 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_violet_avatar_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['key'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Project key must be 2-100 letters/digits, starting with a letter.', regex='^[A-Za-z][A-Za-z0-9]{1,99}$')]),
        ),
    ]
