# Generated by Django 5.1.4 on 2026-09-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_target_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('assigned', 'assigned you'), ('mentioned', 'mentioned you'), ('commented', 'commented'), ('status_changed', 'changed status'), ('watching_updated', 'updated a watched job')], max_length=30),
        ),
    ]
