# Generated by Django 5.1.4 on 2026-10-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_violet_avatar_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'workspace', 'verbose_name_plural': 'workspaces'},
        ),
    ]
