# Generated by Django 5.1.4 on 2026-10-02 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0007_job_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_id', models.CharField(max_length=40)),
                ('file_id', models.CharField(max_length=400)),
                ('file_name', models.CharField(max_length=400)),
                ('location', models.CharField(max_length=300)),
                ('quote', models.TextField()),
                ('drive_url', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AIFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_id', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('direction_ref', models.CharField(default='none', max_length=20)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('severity', models.CharField(max_length=10)),
                ('kind', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('why', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=10)),
                ('confidence', models.CharField(max_length=10)),
                ('evidence', models.ManyToManyField(blank=True, related_name='findings', to='precheck.aievidence')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('not_applicable', 'Not applicable'), ('needs_clarification', 'Needs clarification'), ('cleared', 'Cleared')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='precheck.aifinding')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIPrecheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('partial', 'Partial (budget reached)'), ('failed', 'Failed')], default='running', max_length=20)),
                ('verdict', models.CharField(blank=True, choices=[('ready', 'Ready for review'), ('ready_with_exceptions', 'Ready with exceptions'), ('not_ready', 'Not ready')], max_length=30)),
                ('summary', models.CharField(blank=True, max_length=400)),
                ('coverage_addressed', models.PositiveIntegerField(default=0)),
                ('coverage_total', models.PositiveIntegerField(default=0)),
                ('counts', models.JSONField(default=dict)),
                ('direction_items', models.JSONField(default=list)),
                ('trail', models.JSONField(default=dict)),
                ('progress', models.JSONField(default=list)),
                ('skipped', models.JSONField(default=list)),
                ('failure_reason', models.CharField(blank=True, max_length=500)),
                ('usage', models.JSONField(default=dict)),
                ('models_used', models.JSONField(default=dict)),
                ('versions', models.JSONField(default=dict)),
                ('knowledge_ids', models.JSONField(default=list)),
                ('demo', models.BooleanField(default=False)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prechecks', to='issues.issue')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI pre-check',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aifinding',
            name='precheck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='precheck.aiprecheck'),
        ),
        migrations.AddField(
            model_name='aievidence',
            name='precheck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='precheck.aiprecheck'),
        ),
        migrations.CreateModel(
            name='DirectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_items', to='issues.issue')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(max_length=200)),
                ('folder_url', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_folder', to='issues.issue')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('calls', models.PositiveIntegerField(default=1)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_write_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('prompt_version', models.CharField(blank=True, max_length=40)),
                ('skill_versions', models.JSONField(default=dict)),
                ('knowledge_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('precheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_runs', to='precheck.aiprecheck')),
            ],
        ),
        migrations.AddConstraint(
            model_name='aievidence',
            constraint=models.UniqueConstraint(fields=('precheck', 'evidence_id'), name='evidence_unique_per_run'),
        ),
        migrations.AddConstraint(
            model_name='directionitem',
            constraint=models.UniqueConstraint(fields=('issue', 'ref'), name='direction_ref_unique_per_job'),
        ),
    ]
