# Generated by Django 5.1.4 on 2026-10-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprecheck',
            name='kind',
            field=models.CharField(choices=[('precheck', 'Pre-check'), ('draft', 'Direction Note draft only')], default='precheck', max_length=10),
        ),
        migrations.AddField(
            model_name='directionitem',
            name='basis',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='directionitem',
            name='origin',
            field=models.CharField(choices=[('person', 'Written by a person'), ('ai', 'Drafted by AI')], default='person', max_length=10),
        ),
        migrations.AddField(
            model_name='directionitem',
            name='reason',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
