# Generated by Django 5.1.4 on 2026-10-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precheck', '0002_ai_drafted_direction_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprecheck',
            name='analysis',
            field=models.JSONField(default=dict),
        ),
    ]
