# Generated by Django 5.1.4 on 2026-10-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precheck', '0003_year_on_year_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprecheck',
            name='precheck_type',
            field=models.CharField(default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='aiprecheck',
            name='readiness',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='aiprecheck',
            name='requests',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='jobfolder',
            name='precheck_type',
            field=models.CharField(choices=[('general', 'General'), ('residential_rental', 'Residential rental')], default='general', max_length=30),
        ),
    ]
