# Generated by Django 5.1.4 on 2026-10-05 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def general_meant_no_checklist(apps, schema_editor):
    """Until 5 Oct 2026 "general" meant "no standard checklist". It now means "general business",
    so tasks saved with it go back to letting the pre-check decide from the questionnaire."""
    JobFolder = apps.get_model("precheck", "JobFolder")
    JobFolder.objects.filter(precheck_type="general").update(precheck_type="auto")


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_alter_issue_options'),
        ('precheck', '0004_precheck_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprecheck',
            name='precheck',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='jobfolder',
            name='precheck_type',
            field=models.CharField(choices=[('auto', 'Decide from the questionnaire'), ('residential_rental', 'Residential rental'), ('general', 'General business'), ('investment', 'Investment')], default='auto', max_length=30),
        ),
        migrations.CreateModel(
            name='PrecheckLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_scope', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('client', 'This client'), ('firm', 'All clients of this business nature')], default='client', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Waiting for approval'), ('disabled', 'Switched off')], default='active', max_length=10)),
                ('kind', models.CharField(choices=[('not_needed', 'Not needed'), ('wrong_reason', 'Wrong reason'), ('missed', 'Missed item'), ('other', 'Other')], default='other', max_length=20)),
                ('precheck_type', models.CharField(blank=True, max_length=30)),
                ('item', models.CharField(blank=True, max_length=300)),
                ('note', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precheck_lessons', to='issues.issue')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='precheck.aiprecheck')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(general_meant_no_checklist, migrations.RunPython.noop),
    ]
