# Generated by Django 5.1.4 on 2026-10-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precheck', '0005_requests_and_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfolder',
            name='key_paths',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
