# Generated by Django 5.1.4 on 2026-09-16 09:37

import apps.issues.models
import apps.issues.rank
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('sprints', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=20, unique=True)),
                ('summary', models.CharField(max_length=500)),
                ('description', models.JSONField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('highest', 'Highest'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('lowest', 'Lowest')], default='medium', max_length=10)),
                ('epic_name', models.CharField(blank=True, max_length=150)),
                ('epic_color', models.CharField(blank=True, default='#8777D9', max_length=7)),
                ('story_points', models.FloatField(blank=True, null=True)),
                ('original_estimate', models.DurationField(blank=True, null=True)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('rank', models.CharField(db_index=True, default=apps.issues.rank.rank_first, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('components', models.ManyToManyField(blank=True, related_name='issues', to='projects.component')),
                ('epic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epic_children', to='issues.issue')),
                ('fix_versions', models.ManyToManyField(blank=True, related_name='issues', to='projects.version')),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='workflow.issuetype')),
                ('labels', models.ManyToManyField(blank=True, related_name='issues', to='projects.label')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='issues.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='sprints.sprint')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='workflow.workflowstatus')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.issue')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.issues.models.attachment_upload_path)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='issues.issue')),
            ],
        ),
        migrations.CreateModel(
            name='IssueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='issues.issue')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'issue history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProjectIssueCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue_counter', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watcher_rows', to='issues.issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watcher_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('issue', 'user')},
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_issues', through='issues.Watcher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IssueLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('blocks', 'blocks'), ('is_blocked_by', 'is blocked by'), ('relates_to', 'relates to'), ('duplicates', 'duplicates'), ('clones', 'clones')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='issues.issue')),
                ('target_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='issues.issue')),
            ],
            options={
                'unique_together': {('source_issue', 'target_issue', 'link_type')},
            },
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'status'], name='issues_issu_project_3c2b84_idx'),
        ),
    ]
