# Generated by Django 5.1.4 on 2026-09-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
