# Generated by Django 5.1.4 on 2026-09-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_current_responsible_issue_preparer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='allocated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='budgeted_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
