# Generated by Django 5.1.4 on 2026-09-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issue_allocated_value_issue_budgeted_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='key',
            field=models.CharField(editable=False, max_length=120, unique=True),
        ),
    ]
