# Generated by Django 5.1.4 on 2026-09-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_alter_issue_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
