# Generated by Django 5.1.4 on 2026-10-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_job_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['rank'], 'verbose_name': 'task'},
        ),
    ]
