# Generated by Django 5.1.4 on 2026-09-19 04:13

import apps.workflow.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='card_color_rule',
            field=models.CharField(choices=[('none', 'None'), ('priority', 'By priority'), ('issue_type', 'By issue type'), ('label', 'By label')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='board',
            name='card_fields',
            field=models.JSONField(default=apps.workflow.models._default_card_fields),
        ),
        migrations.AddField(
            model_name='board',
            name='filters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='search.filter'),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='set_current_responsible_to',
            field=models.CharField(choices=[('no_change', 'No change'), ('preparer', 'Set to preparer'), ('reviewer', 'Set to reviewer'), ('assignee', 'Set to assignee')], default='no_change', max_length=20),
        ),
    ]
