# Generated by Django 5.1.4 on 2026-09-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_board_card_color_rule_board_card_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='card_color_style',
            field=models.CharField(choices=[('stripe', 'Left stripe'), ('tint', 'Tinted card')], default='stripe', max_length=10),
        ),
        migrations.AddField(
            model_name='board',
            name='card_colors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='board',
            name='card_color_rule',
            field=models.CharField(choices=[('none', 'None'), ('priority', 'By priority'), ('issue_type', 'By issue type'), ('label', 'By label'), ('due_date', 'By due date')], default='none', max_length=20),
        ),
    ]
