# Generated by Django 5.1.4 on 2026-09-30 14:54

from django.db import migrations, models

# Sentence case for the default statuses. Only names still exactly equal to an old default are
# renamed — anything a team renamed itself is left alone.
RENAMES = {"To Do": "To do", "In Progress": "In progress", "In Review": "In review"}


def sentence_case_defaults(apps, schema_editor):
    WorkflowStatus = apps.get_model("workflow", "WorkflowStatus")
    Board = apps.get_model("workflow", "Board")
    for old, new in RENAMES.items():
        WorkflowStatus.objects.filter(name=old).update(name=new)
    for board in Board.objects.all():
        columns = board.column_config or []
        changed = False
        for col in columns:
            if isinstance(col, dict) and col.get("name") in RENAMES:
                col["name"] = RENAMES[col["name"]]
                changed = True
        if changed:
            board.column_config = columns
            board.save(update_fields=["column_config"])


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_board_color_coding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstatus',
            name='category',
            field=models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('done', 'Done')], default='todo', max_length=20),
        ),
        migrations.RunPython(sentence_case_defaults, migrations.RunPython.noop),
    ]
