# Generated by Django 5.1.4 on 2026-10-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_table_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desktop_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
