# Generated by Django 5.1.4 on 2026-09-25 12:42

from django.db import migrations, models


def rwca_requires_projects(apps, schema_editor):
    # RWCA works project-by-project; every other client can have jobs without a project.
    Client = apps.get_model("clients", "Client")
    Client.objects.filter(name__iexact="RWCA").update(requires_projects=True)


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='requires_projects',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(rwca_requires_projects, migrations.RunPython.noop),
    ]
