# Generated by Django 5.1.4 on 2026-10-04 14:08

from collections import Counter

import django.db.models.deletion
from django.db import migrations, models


def place_clients_in_workspaces(apps, schema_editor):
    """Each existing client (now a sub-workspace) goes into the team (now a workspace) that most
    of its projects already belong to; a client with no team-owned projects stays unplaced.
    Then a project with a client but no team joins its client's team, so the hierarchy reads
    the same from both ends."""
    Client = apps.get_model("clients", "Client")
    Project = apps.get_model("projects", "Project")
    for client in Client.objects.filter(team__isnull=True):
        teams = Counter(
            Project.objects.filter(client=client, primary_team__isnull=False).values_list("primary_team_id", flat=True)
        )
        if teams:
            client.team_id = teams.most_common(1)[0][0]
            client.save(update_fields=["team"])
    for project in Project.objects.filter(primary_team__isnull=True, client__team__isnull=False).select_related("client"):
        project.primary_team_id = project.client.team_id
        project.save(update_fields=["primary_team"])


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_requires_projects'),
        ('teams', '0004_alter_team_options'),
        ('projects', '0010_alter_project_options_alter_project_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'sub-workspace', 'verbose_name_plural': 'sub-workspaces'},
        ),
        migrations.AddField(
            model_name='client',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='teams.team'),
        ),
        migrations.RunPython(place_clients_in_workspaces, migrations.RunPython.noop),
    ]
